<div class="row">

    <div class="content-frame-top">
        <div class="page-title">
            <h2><span class="fa fa-list"></span> Despesas</h2>
        </div>
    </div>

    <div class="col-md-12">
        <div class="panel panel-default">

            <div class="panel-heading">
                <div class="pull-left">
                    <input type="text" name="data" class="form-control" id="calendario-mes-ano"/>
                </div>

                <div class="pull-right">
                    <a class="btn btn-primary btn-rounded"
                       href="<?php echo $this->url('despesa/default', array('action' => 'salvar')); ?>">
                        <span class="fa fa-plus"></span> Nova despesa
                    </a>
                </div>
            </div>

            <div class="panel-body">
                <div class="table-responsive">
                    <table class="table table-condensed table-striped">
                        <thead>
                            <tr>
                                <th>Descrição</th>
                                <th>Pagamento</th>
                                <th>Data vencimento</th>
                                <th>Categoria</th>
                                <th>Conta</th>
                                <th>Valor</th>
                                <th>Ação</th>
                            </tr>
                        </thead>
                        <tbody>
                            <tr>
                                <td><input class="form-control" type="text" name="descricao"></td>
                                <td>
                                    <select name="pagamento" class="form-control">
                                        <option value=""> ==== </option>
                                        <option value="S">Efetuado</option>
                                        <option value="N">Não efetuado</option>
                                    </select>
                                </td>
                                <td class="input-group">
                                    <input class="form-control" type="text" name="data_inicio" data-mascara="mascara-data-br2" placeholder="De">
                                    <input class="form-control" type="text" name="data_fim"    data-mascara="mascara-data-br2" placeholder="Até">
                                </td>
                                <td><input class="form-control" type="text" name="categoria"></td>
                                <td><input class="form-control" type="text" name="conta"></td>
                                <td><input class="form-control" type="text" name="valor" data-mascara="dinheiro-br2"></td>
                                <td>
                                    <button type="submit" class="btn btn-default" id="filtro-tabela-submit">
                                        <span class="fa fa-filter"></span>Filtrar
                                    </button>
                                </td>
                            </tr>

                            <?php foreach ($despesas as $imprimir) : ?>
                                <tr>
                                    <td><?php echo $this->escapeHtml($imprimir->descricao);      ?></td>
                                    <td><?php echo $this->escapeHtml($imprimir->pagamento);      ?></td>
                                    <td><?php echo $this->escapeHtml($imprimir->data_vencimento);?></td>
                                    <td><?php echo $this->escapeHtml($imprimir->dca_nome);       ?></td>
                                    <td><?php echo $this->escapeHtml($imprimir->con_nome);       ?></td>
                                    <td><?php echo $this->escapeHtml($imprimir->valor);          ?></td>
                                    <td>
                                        <?php
                                            echo $this->partial('partial/btn_crud.phtml',
                                            array(
                                                'rota'   => 'despesa/default',
                                                'id'     => $imprimir->id,
                                                'action' => array('editar', 'deletar')
                                            ));
                                        ?>
                                    </td>
                                </tr>
                            <?php endforeach; ?>
                        </tbody>
                    </table>

                    <!--Início paginação-->
                    <?php
                        echo $this->paginationControl(
                            $this->despesas,
                            'sliding',
                            'partial/paginator.phtml',
                            array(
                                'route' => 'desésa'
                            )
                        );
                    ?>
                    <!--Fim paginação-->

                </div>
            </div>
        </div>
    </div>

     <div class="col-md-12">
        <div class="col-md-2 pull-right">
            <div class="widget widget-default saldo-atual-index">
                <div class="widget-title">Total</div>
                <div class="widget-int">R$ <span data-toggle="counter"><?php echo number_format($total, 2, ',', '.') ?></span></div>
            </div>
        </div>

        <div class="col-md-2 pull-right">
            <div class="widget widget-default text-success saldo-atual-index">
                <div class="widget-title">Despesas pagas</div>
                <div class="widget-int">R$ <span data-toggle="counter"><?php echo number_format($totalRecebido, 2, ',', '.') ?></span></div>
            </div>
        </div>

        <div class="col-md-2 pull-right">
            <div class="widget widget-default text-danger saldo-atual-index">
                <div class="widget-title">Despesas pendentes</div>
                <div class="widget-int">R$ <span data-toggle="counter"><?php echo number_format($totalPendente, 2, ',', '.') ?></span></div>
            </div>
        </div>
    </div>

</div>