<div class="row">

    <div class="col-md-12">
        <?php
            $form->setAttribute('action', $this->url('despesa-subcategoria/default', array('action' => 'salvar')));
            $form->prepare();
        ?>

        <?php echo $this->form()->openTag($form); ?>
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><span class="glyphicon glyphicon-floppy-saved"></span> Nova subcategoria</h3>
            </div>

            <div class="panel-body">
                <div class="form-group">
                    <label class="col-md-3 col-xs-2 control-label">Categoria</label>
                    <div class="col-md-3 col-xs-10">
                        <?php
                            echo $this->formHidden($form->get('csrf'));
                            echo $this->formRow($form->get('fk_categoria')->setValueOptions($categorias));
                        ?>
                    </div>
                </div>

                <div class="form-group">
                    <label class="col-md-3 col-xs-2 control-label">Nome</label>
                    <div class="col-md-3 col-xs-10">
                        <?php echo $this->formRow($form->get('nome')); ?>
                    </div>
                </div>
            </div>

            <div class="panel-footer">
                <div class="pull-right">
                    <a class="btn btn-default"
                       href="<?php echo $this->url('despesa-categoria'); ?>">
                        <span class="fa fa-arrow-left"></span> Voltar
                    </a> &nbsp;&nbsp;

                    <button type="submit" class="btn btn-primary">
                        <span class="fa fa-save"></span> Salvar
                    </button>
                </div>
            </div>

        </div>
        <?php echo $this->form()->closeTag(); ?>

    </div>
</div>