<div class="row">
    
    <div class="col-md-12">
        <?php
            $form->setAttribute('action', $this->url('receita-subcategoria/default', array('action' => 'editar', 'id' => $id)));
            $form->prepare();
        ?>
        
        <?php echo $this->form()->openTag($form); ?>
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><span class="glyphicon glyphicon-floppy-saved"></span> Editar categoria</h3>
            </div>
            
            <div class="panel-body">
                <div class="form-group">
                    <label class="col-md-3 col-xs-2 control-label">Categoria</label>
                    <div class="col-md-3 col-xs-10">                                                                                
                        <?php echo $this->formRow($form->get('fk_categoria')->setValueOptions($fk_categoria)); ?>
                    </div>
                </div>
                
                <div class="form-group">
                    <label class="col-md-3 col-xs-2 control-label">Nome</label>
                    <div class="col-md-3 col-xs-10">
                        <?php 
                            echo $this->formHidden($form->get('id'));
                            echo $this->formHidden($form->get('csrf'));
                            echo $this->formRow($form->get('nome')); 
                        ?>
                    </div>
                </div>
            </div>
            
            <div class="panel-footer">  
                <div class="pull-right">
                    <a class="btn btn-default"
                        href="<?php echo $this->url('receita-subcategoria'); ?>">
                         <span class="fa fa-arrow-left"></span> Voltar
                    </a> &nbsp;&nbsp;

                    <button type="submit" class="btn btn-primary pull-right">
                        <span class="fa fa-save"></span> Editar
                    </button>
                </div>                
            </div>           
            
        </div>   
        <?php echo $this->form()->closeTag(); ?>
        
    </div>
</div>