<div class="row">

    <div class="content-frame-top">                        
        <div class="page-title">                    
            <h2><span class="glyphicon glyphicon-floppy-saved"></span> Editar registro</h2>
        </div>                                                                                                
    </div>

    <div class="col-md-12">
        <?php
            $form->setAttribute('action', $this->url('tipo/default', array('action' => 'editar', 'id' => $id)));
            $form->prepare();
        ?>
        
        <?php echo $this->form()->openTag($form); ?>
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Editar cliente</h3>
            </div>
            
            <div class="panel-body">
                <div class="form-group">
                    <label class="col-md-3 col-xs-12 control-label">Nome</label>
                    <div class="col-md-6 col-xs-12">
                        <?php 
                            echo $this->formHidden($form->get('id'));
                            echo $this->formHidden($form->get('csrf'));
                            echo $this->formRow($form->get('nome')); 
                        ?>
                    </div>
                </div>
         
            
                <div class="form-group">
                    <label class="col-md-3 control-label">Situação</label>
                    <div class="col-md-2">                                                                                
                        <?php echo $this->formRow($form->get('situacao')); ?>
                    </div>
                </div>
            </div>
            
            <div class="panel-footer">    
                <a class="btn btn-default"
                   href="<?php echo $this->url('tipo/default'); ?>">
                    <span class="fa fa-arrow-left"></span> Voltar
                </a>
                
                <button type="submit" class="btn btn-primary pull-right">
                    <span class="fa fa-save"></span> Editar
                </button>
            </div>           
            
        </div>   
        <?php echo $this->form()->closeTag(); ?>
        
    </div>
</div>