<div class="row">

    <div class="content-frame-top">                        
        <div class="page-title">                    
            <h2><span class="fa fa-list"></span> Lista de registros</h2>
        </div>                                                                                                
    </div>

    <div class="col-md-12">
        <div class="panel panel-default">
            
            <div class="panel-heading">                                
                <h3 class="panel-title">Usuários</h3>
                
                <div class="pull-right">
                    <a class="btn btn-primary btn-rounded"
                       href="<?php echo $this->url('tipo/default', array('action' => 'salvar')); ?>">
                        <span class="fa fa-plus"></span> Novo registro
                    </a>
                </div>                
            </div>
            
            <div class="panel-body">
                <div class="table-responsive">
                    <table class="table table-condensed table-striped">
                        <thead>
                            <tr>
                                <th>ID</th>
                                <th>Nome</th>
                                <th>Situação</th>
                                <th>Ação</th>
                            </tr>
                        </thead>
                        <tbody>
                            <tr>
                                <td><input class="form-control" type="text"></td>
                                <td><input class="form-control" type="text"></td>
                                <td><input class="form-control" type="text"></td>
                                <td>
                                    <button class="btn btn-default" type="button"> 
                                        <span class="fa fa-filter"></span>Filtrar
                                    </button>
                                </td>
                            </tr>
                            
                            <?php foreach ($tipos as $imprimir) : ?>
                                <tr>
                                    <td><?php echo $this->escapeHtml($imprimir->id);       ?></td>
                                    <td><?php echo $this->escapeHtml($imprimir->nome);     ?></td>
                                    <td><?php echo $this->escapeHtml($imprimir->situacao); ?></td>
                                    <td>
                                        <?php 
                                            echo $this->partial('partial/btn_crud.phtml', 
                                            array(
                                                'rota'   => 'tipo/default',
                                                'id'     => $imprimir->id,
                                                'action' => array('vizualizar', 'editar', 'deletar')
                                            )); 
                                        ?>
                                    </td>
                                </tr>
                            <?php endforeach; ?>
                        </tbody>
                    </table>
                    
                    <!--Início paginação-->
                    <?php                            
                        echo $this->paginationControl(
                            $this->tipos,
                            'sliding',
                            'partial/paginator.phtml',
                            array(
                                'route' => 'pefil'
                            )
                        );
                    ?>                      
                    <!--Fim paginação-->
                    
                </div>
            </div>
        </div>
    </div>
</div>