<div class="row">

    <div class="content-frame-top">                        
        <div class="page-title">                    
            <h2><span class="fa fa-file-text"></span> Informações do registro</h2>
        </div>                                                                                                
    </div>

    <div class="col-md-12">
        <div class="panel panel-default form-horizontal">
            <div class="panel-body">
                <h3><span class="fa fa-info-circle"></span> Usuario</h3>
                <p>Some quick info about this user</p>
            </div>

            <div class="panel-body form-group-separated">                                    
                <div class="form-group">
                    <label class="col-md-4 col-xs-5 control-label">ID</label>
                    <div class="col-md-8 col-xs-7 line-height-30"><?php echo $perfil->id ?></div>
                </div>
                
                <div class="form-group">
                    <label class="col-md-4 col-xs-5 control-label">Nome</label>
                    <div class="col-md-8 col-xs-7 line-height-30"><?php echo $perfil->nome ?></div>
                </div>
                
                <div class="form-group">
                    <label class="col-md-4 col-xs-5 control-label">Situação</label>
                    <div class="col-md-8 col-xs-7 line-height-30"><?php echo $perfil->situacao ?></div>
                </div>

                <div class="form-group">
                    <label class="col-md-4 col-xs-5 control-label">Ação</label>
                    <div class="col-md-8 col-xs-7 line-height-30">                       
                        
                        <?php echo $this->partial('partial/btn_crud.phtml', 
                            array(
                                'model'  => 'perfil',
                                'id'     => $perfil->id,
                                'action' => array('editar', 'deletar')
                            )); 
                        ?>
                        
                    </div>
                </div>
            </div>

        </div>
    </div>
</div>