<div class="row">

    <div class="col-md-12">
        <?php
            $form->setAttribute('action', $this->url('cliente/default', array('action' => 'salvar')));
            $form->prepare();
        ?>

        <?php echo $this->form()->openTag($form); ?>
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"> <span class="glyphicon glyphicon-floppy-saved"></span> Novo cliente</h3>
            </div>

            <div class="panel-body">
                <div class="form-group">
                    <label class="col-md-2 col-xs-12 control-label">Nome</label>
                    <div class="col-md-6 col-xs-12">
                        <?php
                        echo $this->formHidden($form->get('csrf'));
                        echo $this->formRow($form->get('nome'));
                        ?>
                    </div>
                </div>

                <div class="form-group">
                    <label class="col-md-2 col-xs-12 control-label">Email</label>
                    <div class="col-md-6 col-xs-12">
                        <?php echo $this->formRow($form->get('email')); ?>
                    </div>
                </div>


                <div class="form-group">
                    <label class="col-md-2 col-xs-12 control-label">Senha</label>
                    <div class="col-md-6 col-xs-12">
                        <?php echo $this->formRow($form->get('senha')); ?>
                    </div>
                </div>


                <div class="form-group">
                    <label class="col-md-2 col-xs-12 control-label">Confirma senha</label>
                    <div class="col-md-6 col-xs-12">
                        <?php echo $this->formRow($form->get('senha_confirma')); ?>
                    </div>
                </div>
            </div>

            <div class="panel-footer">
                <div class="pull-right">
                    <a class="btn btn-default"
                       href="<?php echo $this->url('cliente'); ?>">
                        <span class="fa fa-arrow-left"></span> Voltar
                    </a> &nbsp;&nbsp;

                    <button type="submit" class="btn btn-primary">
                        <span class="fa fa-save"></span> Salvar
                    </button>
                </div>
            </div>

        </div>
        <?php echo $this->form()->closeTag(); ?>

    </div>
</div>