<div class="row">

    <div class="content-frame-top">                        
        <div class="page-title">                    
            <h2><span class="fa fa-file-text"></span> Informações do registro</h2>
        </div>                                                                                                
    </div>

    <div class="col-md-12">
        <div class="panel panel-default form-horizontal">
            <div class="panel-body">
                <h3><span class="fa fa-info-circle"></span> Cliente</h3>
                <p>Some quick info about this user</p>
            </div>

            <div class="panel-body form-group-separated">                                    
                <div class="form-group">
                    <label class="col-md-4 col-xs-5 control-label">ID</label>
                    <div class="col-md-8 col-xs-7 line-height-30"><?php echo $cliente->getId() ?></div>
                </div>
                <div class="form-group">
                    <label class="col-md-4 col-xs-5 control-label">Nome</label>
                    <div class="col-md-8 col-xs-7 line-height-30"><?php echo $cliente->getNome() ?></div>
                </div>
                <div class="form-group">
                    <label class="col-md-4 col-xs-5 control-label">Email</label>
                    <div class="col-md-8 col-xs-7"><?php echo $cliente->getEmail() ?></div>
                </div>

                <div class="form-group">
                    <label class="col-md-4 col-xs-5 control-label">Data criação</label>
                    <div class="col-md-8 col-xs-7 line-height-30"><?php echo $cliente->getCriado() ?></div>
                </div>
                
                <div class="form-group">
                    <label class="col-md-4 col-xs-5 control-label">Ultima modificação</label>
                    <div class="col-md-8 col-xs-7 line-height-30"><?php echo $cliente->getModificado() ?></div>
                </div>
                
                <div class="form-group">
                    <label class="col-md-4 col-xs-5 control-label">Situação</label>
                    <div class="col-md-8 col-xs-7 line-height-30"><?php echo $cliente->getSituacao() ?></div>
                </div>

                <div class="form-group">
                    <label class="col-md-4 col-xs-5 control-label">Ação</label>
                    <div class="col-md-8 col-xs-7 line-height-30">                       
                        
                        <?php echo $this->partial('partial/btn_crud.phtml', 
                            array(
                                'model'  => 'cliente',
                                'id'     => $cliente->getId(),
                                'action' => array('editar', 'deletar')
                            )); 
                        ?>
                        
                    </div>
                </div>
            </div>

        </div>
    </div>
</div>